In [119]:

import pandas as pd

In [120]:
#1_ Load the file students.csv and make sure Score Date is parsed as datetime

import pandas as pd

df = pd.read_csv(
    "students.csv",
    parse_dates=["Score Date"])
df.head()

   Student ID    Name  Age  Grade    Subject        City  Passed Score Date
0           1   Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2    Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3    Omar   19   65.0       Math        Giza   False 2025-01-20
3           4    Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5  Khaled   45   55.0    Physics    Mansoura   False 2025-02-28

In [121]:
print(df["Score Date"].dtype)

datetime64[ns]

In [122]:
# 2_ Print the shape, columns list, and data types of the DataFrame

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("Data Types:")
df.dtypes

Shape: (9, 8)
Columns: ['Student ID', 'Name', 'Age', 'Grade', 'Subject', 'City', 'Passed', 'Score Date']
Data Types:

Student ID             int64
Name                  object
Age                    int64
Grade                float64
Subject               object
City                  object
Passed                  bool
Score Date    datetime64[ns]
dtype: object

In [123]:
#3_ Show the first 7 rows and the last 3 rows

df.head(7)

   Student ID    Name  Age  Grade    Subject        City  Passed Score Date
0           1   Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2    Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3    Omar   19   65.0       Math        Giza   False 2025-01-20
3           4    Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5  Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
5           6    Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7    Yara   30   89.0       Math       Cairo    True        NaT

In [124]:

df.tail(3)

   Student ID     Name  Age  Grade    Subject   City  Passed Score Date
6           7     Yara   30   89.0       Math  Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry   Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry   Giza    True 2025-03-12

In [125]:
#4_ Show how many missing values in each column

df.isnull().sum()

Student ID    0
Name          0
Age           0
Grade         1
Subject       0
City          0
Passed        0
Score Date    1
dtype: int64

In [126]:
#5_ What is the average, minimum, and maximum Grade

print(df["Grade"].mean())
print(df["Grade"].min())
print(df["Grade"].max())

76.375
55.0
92.0

In [127]:
#6_ How many unique cities are there? List them
# Number of unique cities
num_cities = df["City"].nunique()
print("Number of unique cities:", num_cities)

# List unique cities
unique_cities = df["City"].unique()
print("Unique cities:", unique_cities)

Number of unique cities: 4
Unique cities: ['Cairo' 'Alexandria' 'Giza' 'Mansoura']

In [128]:
#7_ Use value_counts() to show how many students per Subject

print(df["Subject"].value_counts())

Subject
Math         3
Chemistry    3
Physics      2
English      1
Name: count, dtype: int64

In [129]:
#8_ Select only the columns: Name, Grade, Subject, City

df = df[['Name', 'Grade', 'Subject', 'City']]
print(df)

      Name  Grade    Subject        City
0    Ahmed   88.0       Math       Cairo
1     Sara   92.0    Physics  Alexandria
2     Omar   65.0       Math        Giza
3     Lina   78.0  Chemistry       Cairo
4   Khaled   55.0    Physics    Mansoura
5     Nour    NaN    English  Alexandria
6     Yara   89.0       Math       Cairo
7  Mohamed   72.0  Chemistry        Giza
8  Mohamed   72.0  Chemistry        Giza

In [130]:
#9_ Show all students who Passed and have Grade ≥ 85.

df = pd.read_csv('students.csv')
df_Exc_Std = df[(df['Passed'] == True) & (df['Grade'] >= 85)]
print(df_Exc_Std[['Name', 'Grade', 'City', 'Passed']])

    Name  Grade        City  Passed
0  Ahmed   88.0       Cairo    True
1   Sara   92.0  Alexandria    True
6   Yara   89.0       Cairo    True

In [131]:
#10- Show students whose Name contains the letter "a" or "A" (case insensitive)

Req_students = df[df['Name'].str.contains('a', case=False, na=False)]
print(Req_students)

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True  1/15/2025
1           2     Sara   32   92.0    Physics  Alexandria    True  2/10/2025
2           3     Omar   19   65.0       Math        Giza   False  1/20/2025
3           4     Lina   28   78.0  Chemistry       Cairo    True   3/5/2025
4           5   Khaled   45   55.0    Physics    Mansoura   False  2/28/2025
6           7     Yara   30   89.0       Math       Cairo    True        NaN
7           8  Mohamed   27   72.0  Chemistry        Giza    True  3/12/2025
8           8  Mohamed   27   72.0  Chemistry        Giza    True  3/12/2025

In [132]:
#11- Show students in Cairo or Alexandria with Grade < 80.

students = df[
    (df["City"].isin(["Cairo", "Alexandria"])) &
    (df["Grade"] < 80)]

print(students)

   Student ID  Name  Age  Grade    Subject   City  Passed Score Date
3           4  Lina   28   78.0  Chemistry  Cairo    True   3/5/2025

In [133]:
#12_ •Show students with Grade between 80 and 90 (inclusive).

students = df[(df['Grade'] >= 80) & (df['Grade'] <= 90)]
print(students)

   Student ID   Name  Age  Grade Subject   City  Passed Score Date
0           1  Ahmed   25   88.0    Math  Cairo    True  1/15/2025
6           7   Yara   30   89.0    Math  Cairo    True        NaN

In [134]:
#13_ Using .loc, change Khaled's grade from 55 to 68

df.loc[df['Name'] == 'Khaled', 'Grade'] = 68
print(df[df['Name']=='Khaled'])

   Student ID    Name  Age  Grade  Subject      City  Passed Score Date
4           5  Khaled   45   68.0  Physics  Mansoura   False  2/28/2025

In [135]:
#14_ Add a new column Is_Excellent that is True if Grade ≥ 90, False otherwise (vectorized)

df["Is_Excellent"] = df["Grade"] >= 90
print(df.head())

   Student ID    Name  Age  Grade    Subject        City  Passed Score Date  \
0           1   Ahmed   25   88.0       Math       Cairo    True  1/15/2025
1           2    Sara   32   92.0    Physics  Alexandria    True  2/10/2025
2           3    Omar   19   65.0       Math        Giza   False  1/20/2025
3           4    Lina   28   78.0  Chemistry       Cairo    True   3/5/2025
4           5  Khaled   45   68.0    Physics    Mansoura   False  2/28/2025

   Is_Excellent
0         False
1          True
2         False
3         False
4         False

In [136]:
#15_ Fill missing Grade values with the average Grade

avg_grade = df['Grade'].mean()
df['Grade'] = df['Grade'].fillna(avg_grade)
print(f"Average Grade: {df['Grade'].mean():.2f}")
df.head(10)

Average Grade: 78.00

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False
1,2,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True
2,3,Omar,19,65.0,Math,Giza,False,1/20/2025,False
3,4,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False
4,5,Khaled,45,68.0,Physics,Mansoura,False,2/28/2025,False
5,6,Nour,22,78.0,English,Alexandria,True,1/10/2025,False
6,7,Yara,30,89.0,Math,Cairo,True,NaN,False
7,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False
8,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False

In [137]:
#16_ Fill missing Score Date values with the most common date (mode)

mode_date = df['Score Date'].mode()[0]
df['Score Date'] = df['Score Date'].fillna(mode_date)
df.head(10)

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False
1,2,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True
2,3,Omar,19,65.0,Math,Giza,False,1/20/2025,False
3,4,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False
4,5,Khaled,45,68.0,Physics,Mansoura,False,2/28/2025,False
5,6,Nour,22,78.0,English,Alexandria,True,1/10/2025,False
6,7,Yara,30,89.0,Math,Cairo,True,3/12/2025,False
7,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False
8,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False

In [138]:
#17_ Add a new column Final_Grade = Grade + 5 (bonus points).

df['Final_Grade'] = df['Grade'] + 5
print(df[['Name', 'Grade', 'Final_Grade']].head(10))

      Name  Grade  Final_Grade
0    Ahmed   88.0         93.0
1     Sara   92.0         97.0
2     Omar   65.0         70.0
3     Lina   78.0         83.0
4   Khaled   68.0         73.0
5     Nour   78.0         83.0
6     Yara   89.0         94.0
7  Mohamed   72.0         77.0
8  Mohamed   72.0         77.0

In [139]:
#18_ Create a column Grade_Category using pd.cut with bins

bins = [0, 69, 79, 89, 100]
labels = ['Fail', 'Average', 'Good', 'Excellent']
df['Grade_Category'] = pd.cut(df['Grade'], bins=bins, labels=labels, include_lowest=True)
print(df[['Name', 'Grade', 'Grade_Category']].head(10))

      Name  Grade Grade_Category
0    Ahmed   88.0           Good
1     Sara   92.0      Excellent
2     Omar   65.0           Fail
3     Lina   78.0        Average
4   Khaled   68.0           Fail
5     Nour   78.0        Average
6     Yara   89.0           Good
7  Mohamed   72.0        Average
8  Mohamed   72.0        Average

In [140]:
#19_ Remove the column Student ID

df.drop('Student ID', axis=1, inplace=True)
df.head(10)

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,93.0,Good
1,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,97.0,Excellent
2,Omar,19,65.0,Math,Giza,False,1/20/2025,False,70.0,Fail
3,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,83.0,Average
4,Khaled,45,68.0,Physics,Mansoura,False,2/28/2025,False,73.0,Fail
5,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,83.0,Average
6,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,94.0,Good
7,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average

In [141]:
#20_ •Keep only students who Passed

df = df[df['Passed'] == True].reset_index(drop=True)
df.head(10)

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,93.0,Good
1,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,97.0,Excellent
2,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,83.0,Average
3,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,83.0,Average
4,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,94.0,Good
5,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average
6,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average

In [142]:
#21_ Sort the DataFrame by Grade descending

df = df.sort_values('Grade', ascending=False).reset_index(drop=True)
df.head(10)

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,97.0,Excellent
1,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,94.0,Good
2,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,93.0,Good
3,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,83.0,Average
4,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,83.0,Average
5,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average
6,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average

In [143]:
#22_ Sort by City ascending, then inside each city sort by Grade descending

df = df.sort_values(['City', 'Grade'], ascending=[True, False]).reset_index(drop=True)
df.head(10)

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,97.0,Excellent
1,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,83.0,Average
2,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,94.0,Good
3,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,93.0,Good
4,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,83.0,Average
5,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average
6,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average

In [144]:
#23_ Add a column Rank that ranks students by Grade (1 = highest, handle ties with 'min')

df['Rank'] = df['Grade'].rank(ascending=False, method='min')
df.head(10)

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
0,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,97.0,Excellent,1.0
1,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,83.0,Average,4.0
2,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,94.0,Good,2.0
3,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,93.0,Good,3.0
4,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,83.0,Average,4.0
5,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average,6.0
6,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average,6.0

In [145]:
#24_ Show the top 4 students with the highest grades (use nlargest)

top_4 = df.nlargest(4, 'Grade')
print(top_4[['Name', 'Grade']])

    Name  Grade
0   Sara   92.0
2   Yara   89.0
3  Ahmed   88.0
1   Nour   78.0

In [146]:
#25_ Show the 3 youngest students (use nsmallest on Age)

youngest_3 = df.nsmallest(3, 'Age')
print(youngest_3[['Name', 'Age']])

      Name  Age
1     Nour   22
3    Ahmed   25
5  Mohamed   27

In [147]:
#26_ Find the student(s) with the highest Grade and show their Name and Grade

max_grade = df['Grade'].max()
df.head()

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
0,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,97.0,Excellent,1.0
1,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,83.0,Average,4.0
2,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,94.0,Good,2.0
3,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,93.0,Good,3.0
4,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,83.0,Average,4.0

In [148]:
#27_ After filling missing grades, recalculate the average Grade per Subject

avg_grade_per_subject = df.groupby('Subject')['Grade'].mean()
print(avg_grade_per_subject)

Subject
Chemistry    74.0
English      78.0
Math         88.5
Physics      92.0
Name: Grade, dtype: float64

In [149]:
#28_ •Create a new column City_Avg that shows the average grade of each student's city (using transform)

df['City_Avg'] = df.groupby('City')['Grade'].transform('mean')
df.head(10)

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank,City_Avg
0,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,97.0,Excellent,1.0,85.0
1,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,83.0,Average,4.0,85.0
2,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,94.0,Good,2.0,85.0
3,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,93.0,Good,3.0,85.0
4,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,83.0,Average,4.0,85.0
5,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average,6.0,72.0
6,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,77.0,Average,6.0,72.0

In [150]:
#29_ Show the subject with the highest average grade

highest_average_subject = avg_grade_per_subject.idxmax()
print(f"Subject with highest average grade: {highest_average_subject}")

Subject with highest average grade: Physics